New upstream snapshot

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -22225,6 +22225,67 @@ _ACEOF
 fi
 
 
+{ echo "$as_me:$LINENO: checking whether pci_device_enable is declared" >&5
+echo $ECHO_N "checking whether pci_device_enable is declared... $ECHO_C" >&6; }
+if test "${ac_cv_have_decl_pci_device_enable+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <pciaccess.h>
+
+int
+main ()
+{
+#ifndef pci_device_enable
+  (void) pci_device_enable;
+#endif
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_cv_have_decl_pci_device_enable=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_have_decl_pci_device_enable=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_have_decl_pci_device_enable" >&5
+echo "${ECHO_T}$ac_cv_have_decl_pci_device_enable" >&6; }
+if test $ac_cv_have_decl_pci_device_enable = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_PCI_DEVICE_ENABLE 1
+_ACEOF
+
+fi
+
 
 { echo "$as_me:$LINENO: checking whether XSERVER_LIBPCIACCESS is declared" >&5
 echo $ECHO_N "checking whether XSERVER_LIBPCIACCESS is declared... $ECHO_C" >&6; }
